---
- name: this playbook is to install Apache package and run the service 
  hosts: appserver	#(list of hosts of ubuntu)
  become: true	#(it become root) 
  tasks:
  - name: install apache2
    apt:
     name: apache2 
     state: present   #(present or installed)

  - name: start apache2 service 
    service:
     name: apache2 
     state: started
