---
- name: this playbook is to create user from external file
  hosts: all	
  become: true	 
  vars_files:
   - user.yml 
  tasks:
   - name: creating user {{ user }}
     user:
       name: "{{ user }}"
